// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import static boxconnector.proxies.microflows.Microflows.copyFolderImpl;

/**
 * Used to create a copy of a folder in another folder. 
 * The original version of the folder will not be altered.
 * 
 * 
 * Required:
 * SrcBoxFolder: The source folder to copy.
 * The _id attribute is required.
 * 
 * DestBoxFolder: The destination folder where to copy.
 * The _id attribute is required.
 * 
 * Optional
 * NewName: The new name of the folder copy.
 */
public class CopyFolder extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __SrcBoxFolder;
	private boxconnector.proxies.BoxFolder SrcBoxFolder;
	private IMendixObject __DestBoxFolder;
	private boxconnector.proxies.BoxFolder DestBoxFolder;
	private java.lang.String NewName;

	public CopyFolder(IContext context, IMendixObject SrcBoxFolder, IMendixObject DestBoxFolder, java.lang.String NewName)
	{
		super(context);
		this.__SrcBoxFolder = SrcBoxFolder;
		this.__DestBoxFolder = DestBoxFolder;
		this.NewName = NewName;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.SrcBoxFolder = __SrcBoxFolder == null ? null : boxconnector.proxies.BoxFolder.initialize(getContext(), __SrcBoxFolder);

		this.DestBoxFolder = __DestBoxFolder == null ? null : boxconnector.proxies.BoxFolder.initialize(getContext(), __DestBoxFolder);

		// BEGIN USER CODE
		boxconnector.proxies.BoxFolder boxFolder = copyFolderImpl(getContext(), SrcBoxFolder, DestBoxFolder, NewName);
		
		if(boxFolder != null) {
			return boxFolder.getMendixObject();
		} else {
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "CopyFolder";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
