// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import static boxconnector.proxies.microflows.Microflows.createFolderImpl;

/**
 * Used to create a new empty folder. 
 * The new folder will be created inside of the specified parent folder
 * 
 * Required
 * FolderName: The desired name for the folder
 * 
 * BoxFolder: The parent folder.
 * The _id attribute is required.
 */
public class CreateFolder extends CustomJavaAction<IMendixObject>
{
	private java.lang.String FolderName;
	private IMendixObject __BoxFolderParam;
	private boxconnector.proxies.BoxFolder BoxFolderParam;

	public CreateFolder(IContext context, java.lang.String FolderName, IMendixObject BoxFolderParam)
	{
		super(context);
		this.FolderName = FolderName;
		this.__BoxFolderParam = BoxFolderParam;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.BoxFolderParam = __BoxFolderParam == null ? null : boxconnector.proxies.BoxFolder.initialize(getContext(), __BoxFolderParam);

		// BEGIN USER CODE
		boxconnector.proxies.BoxFolder boxFolder = createFolderImpl(getContext(), this.FolderName, this.BoxFolderParam);
		if (boxFolder != null)
			return boxFolder.getMendixObject();
		else
			return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "CreateFolder";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
