// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.createFileSharedLinkImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Used to create a shared link for this particular folder. 
 * In order to disable a shared link set the SharedLink parameter to empty.
 * 
 * Required
 * BoxFolder: The folder for which to create a SharedLink
 * The _id attribute is required
 * 
 * SharedLink: An object representing this items shared link and associated permissions
 * 
 * access: The level of access required for this shared link. Can be open, company, collaborators, or null to get default share level.
 * 
 * unshared_at: The day that this link should be disabled at.
 * 
 * password: Requiring a password before viewing a shared link.
 * 
 * permissions: The set of permissions that apply to this link
 * 
 * effective_access: The access level set by the enterprise administrator. This will override any previous access levels set for the shared link and prevent any less-restrictive access levels to be set.
 */
public class CreateFileSharedLink extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __BoxFileParameter1;
	private boxconnector.proxies.BoxFile BoxFileParameter1;
	private IMendixObject __SharedLinkParameter1;
	private boxconnector.proxies.SharedLink SharedLinkParameter1;

	public CreateFileSharedLink(IContext context, IMendixObject BoxFileParameter1, IMendixObject SharedLinkParameter1)
	{
		super(context);
		this.__BoxFileParameter1 = BoxFileParameter1;
		this.__SharedLinkParameter1 = SharedLinkParameter1;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.BoxFileParameter1 = __BoxFileParameter1 == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParameter1);

		this.SharedLinkParameter1 = __SharedLinkParameter1 == null ? null : boxconnector.proxies.SharedLink.initialize(getContext(), __SharedLinkParameter1);

		// BEGIN USER CODE
		boxconnector.proxies.BoxFile boxFile = createFileSharedLinkImpl(getContext(), BoxFileParameter1, SharedLinkParameter1);
		
		if (boxFile != null)
			return boxFile.getMendixObject();
		else
			return null;
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "CreateFileSharedLink";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
