// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.createMetadataOnFileImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Used to create the metadata template instance for a corresponding Box file. When creating metadata, only values that adhere to the metadata template schema will be accepted.
 * 
 * Required
 * BoxFile
 * The _id attribute is required
 * 
 * MetadataValues: Custom value(s) defined by a user or application
 * 
 * Scope: The scope of the object.
 * 
 * BoxTemplate: The template to use.
 * The templateKey attribute is required
 * At least 1 MetadataValue must be provided with type and corresponding value.
 */
public class CreateMetadataOnFile extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __BoxFileParam;
	private boxconnector.proxies.BoxFile BoxFileParam;
	private IMendixObject __BoxTemplateParam;
	private boxconnector.proxies.BoxTemplate BoxTemplateParam;
	private boxconnector.proxies.MetadataScope Scope;

	public CreateMetadataOnFile(IContext context, IMendixObject BoxFileParam, IMendixObject BoxTemplateParam, java.lang.String Scope)
	{
		super(context);
		this.__BoxFileParam = BoxFileParam;
		this.__BoxTemplateParam = BoxTemplateParam;
		this.Scope = Scope == null ? null : boxconnector.proxies.MetadataScope.valueOf(Scope);
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.BoxFileParam = __BoxFileParam == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParam);

		this.BoxTemplateParam = __BoxTemplateParam == null ? null : boxconnector.proxies.BoxTemplate.initialize(getContext(), __BoxTemplateParam);

		// BEGIN USER CODE
		Boolean result = createMetadataOnFileImpl(getContext(), BoxFileParam, BoxTemplateParam, Scope);
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "CreateMetadataOnFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
