// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.deleteMetadataOnFileImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Used to delete the template instance.
 * 
 * Required
 * BoxFile
 * The _id attribute is required.
 * 
 * Scope: the scope of the template.
 * 
 * BoxTemplate
 * The templateKey attribute is required.
 */
public class DeleteMetadataOnFile extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __BoxFileParam;
	private boxconnector.proxies.BoxFile BoxFileParam;
	private boxconnector.proxies.MetadataScope Scope;
	private IMendixObject __BoxTemplateParam;
	private boxconnector.proxies.BoxTemplate BoxTemplateParam;

	public DeleteMetadataOnFile(IContext context, IMendixObject BoxFileParam, java.lang.String Scope, IMendixObject BoxTemplateParam)
	{
		super(context);
		this.__BoxFileParam = BoxFileParam;
		this.Scope = Scope == null ? null : boxconnector.proxies.MetadataScope.valueOf(Scope);
		this.__BoxTemplateParam = BoxTemplateParam;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.BoxFileParam = __BoxFileParam == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParam);

		this.BoxTemplateParam = __BoxTemplateParam == null ? null : boxconnector.proxies.BoxTemplate.initialize(getContext(), __BoxTemplateParam);

		// BEGIN USER CODE
		Boolean result = deleteMetadataOnFileImpl(getContext(), BoxFileParam, BoxTemplateParam, Scope);
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "DeleteMetadataOnFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
