// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.deleteCollaborationImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Used to delete a single collaboration.
 * 
 * Required
 * BoxCollaboration
 * The _id attribute is required.
 */
public class DeleteCollaboration extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __BoxCollaborationParameter1;
	private boxconnector.proxies.BoxCollaboration BoxCollaborationParameter1;

	public DeleteCollaboration(IContext context, IMendixObject BoxCollaborationParameter1)
	{
		super(context);
		this.__BoxCollaborationParameter1 = BoxCollaborationParameter1;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.BoxCollaborationParameter1 = __BoxCollaborationParameter1 == null ? null : boxconnector.proxies.BoxCollaboration.initialize(getContext(), __BoxCollaborationParameter1);

		// BEGIN USER CODE
		Boolean result = deleteCollaborationImpl(getContext(), BoxCollaborationParameter1);
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "DeleteCollaboration";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
