// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.deleteOldVersionImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Discards a specific file version to the trash.
 * 
 * Required
 * 
 * BoxFile
 * The _id attribute is required.
 * 
 * Version :The version Id to discard.
 * 
 * Optional:
 * IfMatchEtag: This is in the etag field of the file object.
 */
public class DeleteOldVersion extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __BoxFileParameter1;
	private boxconnector.proxies.BoxFile BoxFileParameter1;
	private java.lang.String Version;
	private java.lang.String IfMatchEtag;

	public DeleteOldVersion(IContext context, IMendixObject BoxFileParameter1, java.lang.String Version, java.lang.String IfMatchEtag)
	{
		super(context);
		this.__BoxFileParameter1 = BoxFileParameter1;
		this.Version = Version;
		this.IfMatchEtag = IfMatchEtag;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.BoxFileParameter1 = __BoxFileParameter1 == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParameter1);

		// BEGIN USER CODE
		Boolean result = deleteOldVersionImpl(getContext(), BoxFileParameter1, Version, IfMatchEtag);
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "DeleteOldVersion";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
