// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import static boxconnector.proxies.microflows.Microflows.deleteFileImpl;

/**
 * Discards a file to the trash.
 * 
 * Required
 * BoxFile: the file to delete.
 * _id attribute is required.
 * 
 * Optional
 * IfMatchEtag: The etag of the file. If-Match header to prevent race conditions.
 */
public class DeleteFile extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __BoxFileParameter1;
	private boxconnector.proxies.BoxFile BoxFileParameter1;
	private java.lang.String IfMatchEtag;

	public DeleteFile(IContext context, IMendixObject BoxFileParameter1, java.lang.String IfMatchEtag)
	{
		super(context);
		this.__BoxFileParameter1 = BoxFileParameter1;
		this.IfMatchEtag = IfMatchEtag;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.BoxFileParameter1 = __BoxFileParameter1 == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParameter1);

		// BEGIN USER CODE
		Boolean result = deleteFileImpl(getContext(), BoxFileParameter1, IfMatchEtag);
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "DeleteFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
