// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import static boxconnector.proxies.microflows.Microflows.getFileInfoImpl;

/**
 * Used to retrieve the metadata about a file.
 * 
 * 
 * Required
 * BoxFile: the file to delete.
 * _id attribute is required.
 */
public class GetFileInfo extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __BoxFileParameter1;
	private boxconnector.proxies.BoxFile BoxFileParameter1;

	public GetFileInfo(IContext context, IMendixObject BoxFileParameter1)
	{
		super(context);
		this.__BoxFileParameter1 = BoxFileParameter1;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.BoxFileParameter1 = __BoxFileParameter1 == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParameter1);

		// BEGIN USER CODE
		boxconnector.proxies.BoxFile boxFile = getFileInfoImpl(getContext(), BoxFileParameter1);

		if (boxFile != null)
			return boxFile.getMendixObject();
		else
			return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetFileInfo";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
