// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.getFileTasksImpl;
import java.util.LinkedList;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import boxconnector.proxies.BoxTask;

/**
 * Retrieves all of the tasks for given file.
 * 
 * Required
 * BoxFile
 * The _id attribute is required.
 */
public class GetFileTasks extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __BoxFileParameter1;
	private boxconnector.proxies.BoxFile BoxFileParameter1;
	private java.util.List<IMendixObject> __Fields;
	private java.util.List<boxconnector.proxies.BoxTaskFields> Fields;

	public GetFileTasks(IContext context, IMendixObject BoxFileParameter1, java.util.List<IMendixObject> Fields)
	{
		super(context);
		this.__BoxFileParameter1 = BoxFileParameter1;
		this.__Fields = Fields;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.BoxFileParameter1 = __BoxFileParameter1 == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParameter1);

		this.Fields = new java.util.ArrayList<boxconnector.proxies.BoxTaskFields>();
		if (__Fields != null)
			for (IMendixObject __FieldsElement : __Fields)
				this.Fields.add(boxconnector.proxies.BoxTaskFields.initialize(getContext(), __FieldsElement));

		// BEGIN USER CODE
		java.util.List<IMendixObject> result = new LinkedList<IMendixObject>();
		java.util.List<boxconnector.proxies.BoxTask> boxTaskList = getFileTasksImpl(getContext(), BoxFileParameter1, Fields);
		
		if (boxTaskList != null) {
			for (BoxTask comment : boxTaskList) {
				result.add(comment.getMendixObject());
			}

			return result;
		} else {
			return null;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetFileTasks";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
