// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.getFileCommentsImpl;
import java.util.LinkedList;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import boxconnector.proxies.BoxComment;

/**
 * Retrieves the comments on a particular file, if any exist.
 * 
 * Required
 * BoxFile
 * The _id attribute is required
 * 
 * Optional
 * Fields: Attribute(s) to include in the response
 */
public class GetFileComments extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __BoxFileParam;
	private boxconnector.proxies.BoxFile BoxFileParam;
	private java.util.List<IMendixObject> __Fields;
	private java.util.List<boxconnector.proxies.BoxCommentFields> Fields;

	public GetFileComments(IContext context, IMendixObject BoxFileParam, java.util.List<IMendixObject> Fields)
	{
		super(context);
		this.__BoxFileParam = BoxFileParam;
		this.__Fields = Fields;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.BoxFileParam = __BoxFileParam == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParam);

		this.Fields = new java.util.ArrayList<boxconnector.proxies.BoxCommentFields>();
		if (__Fields != null)
			for (IMendixObject __FieldsElement : __Fields)
				this.Fields.add(boxconnector.proxies.BoxCommentFields.initialize(getContext(), __FieldsElement));

		// BEGIN USER CODE
		java.util.List<IMendixObject> result = new LinkedList<IMendixObject>();
		java.util.List<boxconnector.proxies.BoxComment> boxCommentList = getFileCommentsImpl(getContext(), BoxFileParam, Fields);
		
		if (boxCommentList != null) {
			for (BoxComment comment : boxCommentList) {
				result.add(comment.getMendixObject());
			}

			return result;
		} else {
			return null;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetFileComments";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
