// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.getFolderCollaborationsImpl;
import java.util.LinkedList;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import boxconnector.proxies.BoxCollaboration;

/**
 * Use this to get a list of all the collaborations on a folder i.e. all of the users that have access to that folder.
 * 
 * Required
 * BoxFolder: The folder to request
 * The _id attribute is required.
 * 
 * Optional
 * Limit: The maximum number of items to return in a page. The default is 100 and the max is 1000.
 * 
 * Offset: The item at which to begin the response.
 * 
 * Fields: Attribute(s) to include in the response
 * 
 */
public class GetFolderCollaborations extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __BoxFolderParameter1;
	private boxconnector.proxies.BoxFolder BoxFolderParameter1;
	private java.lang.Long Limit;
	private java.lang.Long Offset;
	private java.util.List<IMendixObject> __Fields;
	private java.util.List<boxconnector.proxies.BoxCollaborationFields> Fields;

	public GetFolderCollaborations(IContext context, IMendixObject BoxFolderParameter1, java.lang.Long Limit, java.lang.Long Offset, java.util.List<IMendixObject> Fields)
	{
		super(context);
		this.__BoxFolderParameter1 = BoxFolderParameter1;
		this.Limit = Limit;
		this.Offset = Offset;
		this.__Fields = Fields;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.BoxFolderParameter1 = __BoxFolderParameter1 == null ? null : boxconnector.proxies.BoxFolder.initialize(getContext(), __BoxFolderParameter1);

		this.Fields = new java.util.ArrayList<boxconnector.proxies.BoxCollaborationFields>();
		if (__Fields != null)
			for (IMendixObject __FieldsElement : __Fields)
				this.Fields.add(boxconnector.proxies.BoxCollaborationFields.initialize(getContext(), __FieldsElement));

		// BEGIN USER CODE
		java.util.List<IMendixObject> result = new LinkedList<IMendixObject>();
		java.util.List<boxconnector.proxies.BoxCollaboration> collaborationList = getFolderCollaborationsImpl(
				getContext(), BoxFolderParameter1, Limit, Offset, Fields);

		if (collaborationList != null) {
			for (BoxCollaboration collaboration : collaborationList) {
				result.add(collaboration.getMendixObject());
			}

			return result;
		} else {
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetFolderCollaborations";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
