// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import boxconnector.proxies.BoxItem;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import static boxconnector.proxies.microflows.Microflows.getFolderItemsImpl;
import java.util.LinkedList;

/**
 * Retrieves the files and/or folders contained within this folder without any other metadata about the folder.
 * The mini format is returned for each item by default.
 * 
 * Required
 * BoxFolder
 * The _id attribute is required
 * 
 * Optional
 * Offset: The offset at which to begin the response. An offset of value of 0 will start at the beginning of the folder-listing. Note: If there are hidden items in your previous response, your next offset should be = offset + limit, not the # of records you received back. The default is 0.
 * 
 * Limit: The maximum number of items to return in a page. The default is 100 and the max is 1000.
 * 
 * Fields: Attribute(s) to include in the response
 */
public class GetFolderItems extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __BoxFolderParameter1;
	private boxconnector.proxies.BoxFolder BoxFolderParameter1;
	private java.lang.Long Limit;
	private java.lang.Long Offset;
	private java.util.List<IMendixObject> __Fields;
	private java.util.List<boxconnector.proxies.BoxItemFields> Fields;

	public GetFolderItems(IContext context, IMendixObject BoxFolderParameter1, java.lang.Long Limit, java.lang.Long Offset, java.util.List<IMendixObject> Fields)
	{
		super(context);
		this.__BoxFolderParameter1 = BoxFolderParameter1;
		this.Limit = Limit;
		this.Offset = Offset;
		this.__Fields = Fields;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.BoxFolderParameter1 = __BoxFolderParameter1 == null ? null : boxconnector.proxies.BoxFolder.initialize(getContext(), __BoxFolderParameter1);

		this.Fields = new java.util.ArrayList<boxconnector.proxies.BoxItemFields>();
		if (__Fields != null)
			for (IMendixObject __FieldsElement : __Fields)
				this.Fields.add(boxconnector.proxies.BoxItemFields.initialize(getContext(), __FieldsElement));

		// BEGIN USER CODE
		java.util.List<IMendixObject> listResult = new LinkedList<IMendixObject>();
		java.util.List<boxconnector.proxies.BoxItem> listBoxItem = getFolderItemsImpl(getContext(), BoxFolderParameter1,
				Offset, Limit, Fields);

		if (listBoxItem != null) {
			for (BoxItem item : listBoxItem) {
				listResult.add(item.getMendixObject());
			}

			return listResult;
		} else {
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetFolderItems";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
