// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.getMetadataOnFileImpl;
import java.util.LinkedList;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import boxconnector.proxies.BoxMetadata;

/**
 * Used to retrieve the metadata template instance for a corresponding Box file.
 * 
 * Required
 * 
 * BoxFile
 * The _id attribute is required.
 * 
 * BoxTemplate
 * The templateKey attribute is required.
 * 
 * Scope
 * The scope.
 */
public class GetMetadataOnFile extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __BoxFileParameter1;
	private boxconnector.proxies.BoxFile BoxFileParameter1;
	private IMendixObject __BoxTemplateParameter1;
	private boxconnector.proxies.BoxTemplate BoxTemplateParameter1;
	private boxconnector.proxies.MetadataScope Scope;

	public GetMetadataOnFile(IContext context, IMendixObject BoxFileParameter1, IMendixObject BoxTemplateParameter1, java.lang.String Scope)
	{
		super(context);
		this.__BoxFileParameter1 = BoxFileParameter1;
		this.__BoxTemplateParameter1 = BoxTemplateParameter1;
		this.Scope = Scope == null ? null : boxconnector.proxies.MetadataScope.valueOf(Scope);
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.BoxFileParameter1 = __BoxFileParameter1 == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParameter1);

		this.BoxTemplateParameter1 = __BoxTemplateParameter1 == null ? null : boxconnector.proxies.BoxTemplate.initialize(getContext(), __BoxTemplateParameter1);

		// BEGIN USER CODE
		java.util.List<IMendixObject> listResult = new LinkedList<IMendixObject>();
		java.util.List<boxconnector.proxies.BoxMetadata> listMetadata = getMetadataOnFileImpl(getContext(), BoxFileParameter1, BoxTemplateParameter1, Scope);
		
		if (listMetadata != null) {
			for (BoxMetadata item : listMetadata) {
				listResult.add(item.getMendixObject());
			}

			return listResult;
		} else {
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetMetadataOnFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
