// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.getTrashedFolderImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

/**
 * Retrieves an folder that has been moved to the trash. A 404 will be returned if the folder is not in the trash.
 * 
 * Required
 * BoxFolder: The folder to retrieve.
 * The _id attribute is required.
 * 
 * Optional
 * Fields: Attribute(s) to include in the response
 * 
 */
public class GetTrashedFolder extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __BoxFolderParameter1;
	private boxconnector.proxies.BoxFolder BoxFolderParameter1;
	private java.util.List<IMendixObject> __Fields;
	private java.util.List<boxconnector.proxies.BoxItemFields> Fields;

	public GetTrashedFolder(IContext context, IMendixObject BoxFolderParameter1, java.util.List<IMendixObject> Fields)
	{
		super(context);
		this.__BoxFolderParameter1 = BoxFolderParameter1;
		this.__Fields = Fields;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.BoxFolderParameter1 = __BoxFolderParameter1 == null ? null : boxconnector.proxies.BoxFolder.initialize(getContext(), __BoxFolderParameter1);

		this.Fields = new java.util.ArrayList<boxconnector.proxies.BoxItemFields>();
		if (__Fields != null)
			for (IMendixObject __FieldsElement : __Fields)
				this.Fields.add(boxconnector.proxies.BoxItemFields.initialize(getContext(), __FieldsElement));

		// BEGIN USER CODE
		boxconnector.proxies.BoxFolder boxFolder = getTrashedFolderImpl(getContext(), BoxFolderParameter1, Fields);
		if (boxFolder != null)
			return boxFolder.getMendixObject();
		else
			return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetTrashedFolder";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
