// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.getTokenImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import boxconnector.proxies.AccessToken;

public class GetToken extends CustomJavaAction<IMendixObject>
{
	private java.lang.String Code;
	private java.lang.String State;
	private IMendixObject __BoxApplicationParameter1;
	private boxconnector.proxies.BoxApplication BoxApplicationParameter1;

	public GetToken(IContext context, java.lang.String Code, java.lang.String State, IMendixObject BoxApplicationParameter1)
	{
		super(context);
		this.Code = Code;
		this.State = State;
		this.__BoxApplicationParameter1 = BoxApplicationParameter1;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.BoxApplicationParameter1 = __BoxApplicationParameter1 == null ? null : boxconnector.proxies.BoxApplication.initialize(getContext(), __BoxApplicationParameter1);

		// BEGIN USER CODE
		AccessToken token = getTokenImpl(getContext(), Code, State, BoxApplicationParameter1);

		if(token != null) {
			return token.getMendixObject();
		} else {
			return null;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
