// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.getThumbnailImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Retrieves a thumbnail, or smaller image representation, of this file. 
 * Sizes of 32x32, 64x64, 128x128, and 256x256 can be returned in the .png format and sizes of 32x32, 94x94, 160x160, and 320x320 can be returned in the .jpg format. 
 * Thumbnails can be generated for image and video file formats.
 * 
 * Required
 * BoxFile: 
 * The _id attribute is required
 * 
 * Format: The expected format for the Thumbnail
 * 
 * Optional
 * MinSize
 * MaxSize
 */
public class GetThumbnail extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __BoxFileParam;
	private boxconnector.proxies.BoxFile BoxFileParam;
	private boxconnector.proxies.BoxThumbnailFormat Format;
	private boxconnector.proxies.BoxThumbnailSize MinSize;
	private boxconnector.proxies.BoxThumbnailSize MaxSize;

	public GetThumbnail(IContext context, IMendixObject BoxFileParam, java.lang.String Format, java.lang.String MinSize, java.lang.String MaxSize)
	{
		super(context);
		this.__BoxFileParam = BoxFileParam;
		this.Format = Format == null ? null : boxconnector.proxies.BoxThumbnailFormat.valueOf(Format);
		this.MinSize = MinSize == null ? null : boxconnector.proxies.BoxThumbnailSize.valueOf(MinSize);
		this.MaxSize = MaxSize == null ? null : boxconnector.proxies.BoxThumbnailSize.valueOf(MaxSize);
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.BoxFileParam = __BoxFileParam == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParam);

		// BEGIN USER CODE
		boxconnector.proxies.BoxThumbnail boxThumbnail = getThumbnailImpl(getContext(), BoxFileParam, Format, MaxSize, MinSize);
		if(boxThumbnail != null) {
			return boxThumbnail.getMendixObject();
		} else {
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetThumbnail";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
