// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import boxconnector.proxies.BoxItem;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import static boxconnector.proxies.microflows.Microflows.getTrashedItemsImpl;
import java.util.LinkedList;

/**
 * Retrieves the files and/or folders that have been moved to the trash.
 * 
 * Optional
 * 
 * Limit:  The maximum number of items to return
 * Offset: The item at which to begin the response
 * Fields: Attribute(s) to include in the response
 */
public class GetTrashedItems extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.Long Limit;
	private java.lang.Long Offset;
	private java.util.List<IMendixObject> __Fields;
	private java.util.List<boxconnector.proxies.BoxItemFields> Fields;

	public GetTrashedItems(IContext context, java.lang.Long Limit, java.lang.Long Offset, java.util.List<IMendixObject> Fields)
	{
		super(context);
		this.Limit = Limit;
		this.Offset = Offset;
		this.__Fields = Fields;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.Fields = new java.util.ArrayList<boxconnector.proxies.BoxItemFields>();
		if (__Fields != null)
			for (IMendixObject __FieldsElement : __Fields)
				this.Fields.add(boxconnector.proxies.BoxItemFields.initialize(getContext(), __FieldsElement));

		// BEGIN USER CODE
		java.util.List<boxconnector.proxies.BoxItem> listBoxItem = getTrashedItemsImpl(getContext(), Offset, Limit, Fields);
		
		java.util.List<IMendixObject> listResult = new LinkedList<IMendixObject>();
		if (listBoxItem != null) {
			for (BoxItem item : listBoxItem) {
				listResult.add(item.getMendixObject());
			}

			return listResult;
		} else {
			return null;
		}
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "GetTrashedItems";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
