// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import java.text.ParseException;
import java.util.Date;
import java.util.Iterator;
import com.mendix.thirdparty.org.json.JSONObject;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import boxconnector.proxies.BoxMetadata;
import boxconnector.proxies.BoxMetadataValue;
import boxconnector.util.BoxDateFormat;

public class ParseJsonMetadataResponse extends CustomJavaAction<java.lang.Boolean>
{
	private java.lang.String JsonResponse;
	private java.util.List<IMendixObject> __MetadataList;
	private java.util.List<boxconnector.proxies.BoxMetadata> MetadataList;

	public ParseJsonMetadataResponse(IContext context, java.lang.String JsonResponse, java.util.List<IMendixObject> MetadataList)
	{
		super(context);
		this.JsonResponse = JsonResponse;
		this.__MetadataList = MetadataList;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.MetadataList = new java.util.ArrayList<boxconnector.proxies.BoxMetadata>();
		if (__MetadataList != null)
			for (IMendixObject __MetadataListElement : __MetadataList)
				this.MetadataList.add(boxconnector.proxies.BoxMetadata.initialize(getContext(), __MetadataListElement));

		// BEGIN USER CODE
		JSONObject json = new JSONObject(JsonResponse);

		Iterator<String> keys = json.keys();

		while(keys.hasNext() ) {
			String key = keys.next();
			BoxMetadata metadata = new BoxMetadata(getContext());
			metadata.setkey(key);
			BoxMetadataValue metadataValue = new BoxMetadataValue(getContext());
			Object value = json.get(key);
			if(value instanceof String) {
				String strValue = (String) value;

				try {
					Date date = null;
					if(strValue.endsWith("Z")){
						date = BoxDateFormat.parseZdate(strValue);
					}else {
						date = BoxDateFormat.parse(strValue);
					}
					metadataValue.setdateValue(date);
				} catch (ParseException error) {
					metadataValue.setstringValue((String)value);
				}
			} else if(value instanceof Date) {
				metadataValue.setdateValue((Date)value);
			} else if(value instanceof Long) {
				metadataValue.setfloatValue((Long)value);
			}
			metadataValue.setValue(metadata);

			MetadataList.add(metadata);
		}

		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ParseJsonMetadataResponse";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
