// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import static boxconnector.proxies.microflows.Microflows.permanentlyDeleteFolderImpl;

/**
 * Permanently deletes an folder that is in the trash. The item will no longer exist in Box. This action cannot be undone.
 * 
 * Required
 * BoxFolder: the folder to delete
 * The _id attribute is required.
 */
public class PermanentlyDeleteFolder extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __BoxFolderParameter1;
	private boxconnector.proxies.BoxFolder BoxFolderParameter1;

	public PermanentlyDeleteFolder(IContext context, IMendixObject BoxFolderParameter1)
	{
		super(context);
		this.__BoxFolderParameter1 = BoxFolderParameter1;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.BoxFolderParameter1 = __BoxFolderParameter1 == null ? null : boxconnector.proxies.BoxFolder.initialize(getContext(), __BoxFolderParameter1);

		// BEGIN USER CODE
		Boolean result = permanentlyDeleteFolderImpl(getContext(), BoxFolderParameter1);
		
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "PermanentlyDeleteFolder";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
