// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.preflightCheckImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * The Pre-flight check will verify that a file will be accepted by Box before you send all the bytes over the wire. 
 * It can be used for both first-time uploads, and uploading new versions of an existing File (on /files/[id]/content). 
 * 
 * Preflight checks verify all permissions as if the file was actually uploaded including:
 * 
 *     Folder upload permission
 *     File name collisions
 *     file size caps
 *     folder and file name restrictions
 *     folder and account storage quota
 * 
 * 
 * Required
 * BoxFile
 * The attribute name is requied.
 * 
 * BoxFolder
 * The _id attribute is required.
 */
public class PreflightCheck extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __BoxFileParam;
	private boxconnector.proxies.BoxFile BoxFileParam;
	private IMendixObject __BoxFolderParam;
	private boxconnector.proxies.BoxFolder BoxFolderParam;

	public PreflightCheck(IContext context, IMendixObject BoxFileParam, IMendixObject BoxFolderParam)
	{
		super(context);
		this.__BoxFileParam = BoxFileParam;
		this.__BoxFolderParam = BoxFolderParam;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.BoxFileParam = __BoxFileParam == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParam);

		this.BoxFolderParam = __BoxFolderParam == null ? null : boxconnector.proxies.BoxFolder.initialize(getContext(), __BoxFolderParam);

		// BEGIN USER CODE
		Boolean result = preflightCheckImpl(getContext(), BoxFileParam, BoxFolderParam);
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "PreflightCheck";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
