// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.thirdparty.org.json.JSONObject;
import com.mendix.webui.CustomJavaAction;
import boxconnector.proxies.constants.Constants;

public class PreflightCheckCall extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __BoxFileParam;
	private boxconnector.proxies.BoxFile BoxFileParam;
	private IMendixObject __BoxFolderParam;
	private boxconnector.proxies.BoxFolder BoxFolderParam;
	private IMendixObject __AccessTokenParam;
	private boxconnector.proxies.AccessToken AccessTokenParam;

	public PreflightCheckCall(IContext context, IMendixObject BoxFileParam, IMendixObject BoxFolderParam, IMendixObject AccessTokenParam)
	{
		super(context);
		this.__BoxFileParam = BoxFileParam;
		this.__BoxFolderParam = BoxFolderParam;
		this.__AccessTokenParam = AccessTokenParam;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.BoxFileParam = __BoxFileParam == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParam);

		this.BoxFolderParam = __BoxFolderParam == null ? null : boxconnector.proxies.BoxFolder.initialize(getContext(), __BoxFolderParam);

		this.AccessTokenParam = __AccessTokenParam == null ? null : boxconnector.proxies.AccessToken.initialize(getContext(), __AccessTokenParam);

		// BEGIN USER CODE
		String URL = Constants.getBoxAPI_URL_Files() + "/content";

		HttpURLConnection connection = (HttpURLConnection) new URL(URL).openConnection();
		connection.setRequestMethod("OPTIONS");
		connection.setDoOutput(true);
		connection.addRequestProperty("Authorization", "Bearer " + this.AccessTokenParam.gettoken());
		connection.addRequestProperty("Content-Type", "application/json");
		connection.connect();

		JSONObject params = new JSONObject();
		params.put("name", this.BoxFileParam.getname());

		JSONObject parent = new JSONObject();
		parent.put("id", this.BoxFolderParam.get_id());

		params.put("parent", parent);
		params.put("size", 0);

		OutputStream out = connection.getOutputStream();
		out.write(params.toString().getBytes());
		out.close();

		int status = connection.getResponseCode();

		connection.disconnect();

		if (status == HttpURLConnection.HTTP_OK) {
			return true;
		} else {
			return false;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "PreflightCheckCall";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
