// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.promoteVersionImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * If there are previous versions of this file, this method can be used to promote one of the older versions to the top of the stack. This actually mints a copy of the old version and puts it on the top of the versions stack. The file will have the exact same contents, the same SHA1/etag, and the same name as the original. Other properties such as comments do not get updated to their former values.
 * 
 * Required
 * 
 * BoxFile: The file to update
 * The _id attribute is required
 * 
 * Version: The ID of the file_version that you want to make current.
 */
public class PromoteVersion extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __BoxFileParameter1;
	private boxconnector.proxies.BoxFile BoxFileParameter1;
	private java.lang.String Version;

	public PromoteVersion(IContext context, IMendixObject BoxFileParameter1, java.lang.String Version)
	{
		super(context);
		this.__BoxFileParameter1 = BoxFileParameter1;
		this.Version = Version;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.BoxFileParameter1 = __BoxFileParameter1 == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParameter1);

		// BEGIN USER CODE
		boxconnector.proxies.BoxFileVersion fileVersion = promoteVersionImpl(getContext(), BoxFileParameter1, Version);
		if(fileVersion != null) {
			return fileVersion.getMendixObject();
		} else {
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "PromoteVersion";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
