// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.refreshTokenImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import boxconnector.proxies.AccessToken;

public class RefreshToken extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __AccessTokenParam;
	private boxconnector.proxies.AccessToken AccessTokenParam;

	public RefreshToken(IContext context, IMendixObject AccessTokenParam)
	{
		super(context);
		this.__AccessTokenParam = AccessTokenParam;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.AccessTokenParam = __AccessTokenParam == null ? null : boxconnector.proxies.AccessToken.initialize(getContext(), __AccessTokenParam);

		// BEGIN USER CODE
		AccessToken token = refreshTokenImpl(getContext(), AccessTokenParam);
		if(token != null) {
			return token.getMendixObject();
		} else {
			return null;
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "RefreshToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
