// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.restoreFileImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Restores an item that has been moved to the trash. Default behavior is to restore the item to the folder it was in before it was moved to the trash. If that parent folder no longer exists or if there is now an item with the same name in that parent folder, the new parent folder and/or new name will need to be included in the request.
 * 
 * Required
 * 
 * BoxFile: The file to restore.
 * The _id attribute is required.
 * 
 * Optional
 * 
 * name: The new name for this item
 * 
 * DestBoxFolder: The new parent folder for this item
 * The _id attribute is required.
 */
public class RestoreFile extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __BoxFileParameter1;
	private boxconnector.proxies.BoxFile BoxFileParameter1;
	private java.lang.String Name;
	private IMendixObject __DestBoxFolder;
	private boxconnector.proxies.BoxFolder DestBoxFolder;

	public RestoreFile(IContext context, IMendixObject BoxFileParameter1, java.lang.String Name, IMendixObject DestBoxFolder)
	{
		super(context);
		this.__BoxFileParameter1 = BoxFileParameter1;
		this.Name = Name;
		this.__DestBoxFolder = DestBoxFolder;
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.BoxFileParameter1 = __BoxFileParameter1 == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParameter1);

		this.DestBoxFolder = __DestBoxFolder == null ? null : boxconnector.proxies.BoxFolder.initialize(getContext(), __DestBoxFolder);

		// BEGIN USER CODE
		boxconnector.proxies.BoxFile boxFile = restoreFileImpl(getContext(), BoxFileParameter1, Name, DestBoxFolder);
		
		if (boxFile != null)
			return boxFile.getMendixObject();
		else
			return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "RestoreFile";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
