// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.revokeTokenImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * To revoke an access token, ending the session and logging the user out of Box.
 */
public class RevokeToken extends CustomJavaAction<java.lang.Boolean>
{
	private IMendixObject __AccessTokenParam;
	private boxconnector.proxies.AccessToken AccessTokenParam;

	public RevokeToken(IContext context, IMendixObject AccessTokenParam)
	{
		super(context);
		this.__AccessTokenParam = AccessTokenParam;
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		this.AccessTokenParam = __AccessTokenParam == null ? null : boxconnector.proxies.AccessToken.initialize(getContext(), __AccessTokenParam);

		// BEGIN USER CODE
		Boolean result = revokeTokenImpl(getContext(), AccessTokenParam);
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "RevokeToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
