// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import static boxconnector.proxies.microflows.Microflows.updateCollaborationImpl;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * Used to edit an existing collaboration.
 * 
 * Required
 * BoxCollaboration
 * The _id attribute is required.
 * 
 * Optional
 * UpdateRole: The access level of this collaboration.
 * 
 * UpdateStatus: Whether this collaboration has been accepted
 * This can be set to accepted or rejected by the accessible_by user if the status is pending
 * 
 * UpdateExpiresAt: The time in the future this collaboration will expire
 * 
 * UpdateCanViewPath: Whether view path collaboration feature is enabled or not. 
 */
public class UpdateCollaboration extends CustomJavaAction<IMendixObject>
{
	private IMendixObject __BoxCollaborationParam;
	private boxconnector.proxies.BoxCollaboration BoxCollaborationParam;
	private boxconnector.proxies.CollaborationRole UpdateRole;
	private boxconnector.proxies.CollaborationStatus UpdateStatus;
	private java.util.Date UpdateExpiresAt;
	private boxconnector.proxies.BooleanParameter UpdateCanViewPath;

	public UpdateCollaboration(IContext context, IMendixObject BoxCollaborationParam, java.lang.String UpdateRole, java.lang.String UpdateStatus, java.util.Date UpdateExpiresAt, java.lang.String UpdateCanViewPath)
	{
		super(context);
		this.__BoxCollaborationParam = BoxCollaborationParam;
		this.UpdateRole = UpdateRole == null ? null : boxconnector.proxies.CollaborationRole.valueOf(UpdateRole);
		this.UpdateStatus = UpdateStatus == null ? null : boxconnector.proxies.CollaborationStatus.valueOf(UpdateStatus);
		this.UpdateExpiresAt = UpdateExpiresAt;
		this.UpdateCanViewPath = UpdateCanViewPath == null ? null : boxconnector.proxies.BooleanParameter.valueOf(UpdateCanViewPath);
	}

	@Override
	public IMendixObject executeAction() throws Exception
	{
		this.BoxCollaborationParam = __BoxCollaborationParam == null ? null : boxconnector.proxies.BoxCollaboration.initialize(getContext(), __BoxCollaborationParam);

		// BEGIN USER CODE
		boxconnector.proxies.BoxCollaboration boxC = updateCollaborationImpl(getContext(), BoxCollaborationParam, UpdateStatus, UpdateCanViewPath, UpdateRole, UpdateExpiresAt);
		
		if (boxC != null)
			return boxC.getMendixObject();
		else
			return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "UpdateCollaboration";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
