// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package boxconnector.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import boxconnector.proxies.BoxFileVersion;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import static boxconnector.proxies.microflows.Microflows.viewVersionsImpl;
import java.util.LinkedList;

/**
 * If there are previous versions of this file, this method can be used to retrieve information about the older versions.
 * 
 * Required
 * BoxFile
 * The _id attribute is required
 * 
 * Optional
 * Fields: Attribute(s) to include in the response
 */
public class ViewVersions extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private IMendixObject __BoxFileParam;
	private boxconnector.proxies.BoxFile BoxFileParam;
	private java.util.List<IMendixObject> __Fields;
	private java.util.List<boxconnector.proxies.BoxVersionFields> Fields;

	public ViewVersions(IContext context, IMendixObject BoxFileParam, java.util.List<IMendixObject> Fields)
	{
		super(context);
		this.__BoxFileParam = BoxFileParam;
		this.__Fields = Fields;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		this.BoxFileParam = __BoxFileParam == null ? null : boxconnector.proxies.BoxFile.initialize(getContext(), __BoxFileParam);

		this.Fields = new java.util.ArrayList<boxconnector.proxies.BoxVersionFields>();
		if (__Fields != null)
			for (IMendixObject __FieldsElement : __Fields)
				this.Fields.add(boxconnector.proxies.BoxVersionFields.initialize(getContext(), __FieldsElement));

		// BEGIN USER CODE
		java.util.List<boxconnector.proxies.BoxFileVersion> listVersion = viewVersionsImpl(getContext(), BoxFileParam, Fields);
		if(listVersion != null) {
			java.util.List<IMendixObject> result = new LinkedList<IMendixObject>();
			for(BoxFileVersion fileVersion : listVersion) {
				result.add(fileVersion.getMendixObject());
			}
			return result;
		} else {
			return null;
		}
		
		
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ViewVersions";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
